# Generated by Django 5.0.4 on 2024-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticfiledemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='abc',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
